name: Tests

on:
    push:

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - pypy-3.6
          - pypy-3.7
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - os: macos-latest
            python-version: 'pypy-3.6'
    runs-on:  ${{ matrix.os }}
    name: ${{ matrix.os }} @ ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python setup.py install
      - run: pip install nose pytest
      - run: pytest --doctest-modules sexpdata.py test_sexpdata.py
